#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars

#+BEGIN_EXPORT html
---
layout: post
title:  "The Relevance of Fuzzy Cognitive Mapping Approaches for Assessing Adaptive Capacity and Resilience in Social–Ecological Systems"
date:   2013-10-02
categories: [publications]
---
#+END_EXPORT




Social–Ecological Systems (SES) are complex due to uncertainty related to their nature and their functions. In these systems, decision-making processes and practices of managers are often value-laden and subjective, dominated by their world-views and their own knowledge. People’s knowledge are central in building their adaptive capacity but are seldom taken into account by traditional decision-making approaches in modelling SES management. In this paper, we introduce a Fuzzy Cognitive Mapping approach to study the dynamic behaviour of managers’ systems of practices. As a case study, we aim to assess farmers’ forage management under different climatic scenarios. Results show that summer drought have varying consequences according to farmers’ systems of practices. Fuzzy Cognitive Mapping approaches are particularly relevant in studying systems of practices in SES. Their utilisation is promising for the evaluation of adaptive capacity and resilience in SES at local scale (exploitation, community) and regional scale (ecological areas, country).

---

- Vanwindekens, F. M.; Stilmant, D. & Baret, P. V. (2013), The Relevance of Fuzzy Cognitive Mapping Approaches for Assessing Adaptive Capacity and Resilience in Social–Ecological Systems, in Harris Papadopoulos; Andreas S. Andreou; Lazaros Iliadis & Ilias Maglogiannis, ed., Artificial Intelligence Applications and Innovations, Springer Berlin Heidelberg, pp. 587-596.
- Lien vers la version personnelle de l’article : Vanwindekens, Stilmant, Baret (2013a)
- Lien vers la version publiée de l’article : [[https://dx.doi.org/10.1007/978-3-642-41142-7_59]]
